language: node_js

node_js:
  - "node"
  - "4.2"
  - "0.12"

addons:
  code_climate:
    repo_token: faa41e7818cb4a634132f6634ea612042b53747a421b410c1608b23ff327b9f1

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
